apiVersion: v1
kind: Secret
metadata:
  name: radioflow-secrets
  namespace: radioflow
type: Opaque
stringData:
  # Postgres administrado (ejemplos):
  # - Azure: postgresql://user:pass@host.postgres.database.azure.com:5432/radioflow?sslmode=require
  # - RDS:   postgresql://user:pass@host.rds.amazonaws.com:5432/radioflow?sslmode=require
  DATABASE_URL: "postgresql://radioflow:CAMBIAR@postgres.example.com:5432/radioflow?sslmode=require"

  # Redis administrado (opcional):
  # - Azure Cache: rediss://:<pass>@host.redis.cache.windows.net:6380
  # - ElastiCache: redis://host:6379
  REDIS_URL: "redis://redis.example.com:6379"

  JWT_SECRET: "cambiar-en-prod-minimo-32-caracteres"

