apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radioflow-api
  namespace: radioflow
spec:
  rules:
    - host: radioflow.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 4000

