ALTER TABLE "Station" ADD COLUMN "cabCrossfadeSec" REAL NOT NULL DEFAULT 4;
ALTER TABLE "Station" ADD COLUMN "cabReferenceGainDb" REAL NOT NULL DEFAULT 0;
ALTER TABLE "Station" ADD COLUMN "cabWebAudioEngine" INTEGER NOT NULL DEFAULT 1;

ALTER TABLE "MediaAsset" ADD COLUMN "playbackGainDb" REAL NOT NULL DEFAULT 0;
